language: bash
sudo: required
dist: trusty
env:
- OS=ubuntu ARCH=amd64 DIST=xenial
- OS=ubuntu ARCH=amd64 DIST=bionic
- OS=debian ARCH=amd64 DIST=stretch
- OS=debian ARCH=armhf DIST=stretch
- OS=debian ARCH=armel DIST=stretch
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository --yes ppa:ev3dev/tools/
- sudo apt-get update
- sudo apt-get install --yes pbuilder-ev3dev gobject-introspection
before_script:
- pbuilder-ev3dev base
- git checkout ev3dev-$DIST
- git merge ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
script:
- pbuilder-ev3dev build
