sudo: required
dist: trusty
env:
- OS=debian ARCH=amd64 DIST=jessie
- OS=debian ARCH=i386 DIST=jessie
- OS=debian ARCH=armhf DIST=jessie
- OS=raspbian ARCH=armhf DIST=jessie
- OS=debian ARCH=armel DIST=jessie
cache:
  directories:
  - "$HOME/cache"
before_install:
- wget --directory-prefix=/tmp https://raw.githubusercontent.com/ev3dev/ev3dev-buildscripts/master/pbuilder-ev3dev
- chmod +x /tmp/pbuilder-ev3dev
- "/tmp/pbuilder-ev3dev deps"
before_script:
- "/tmp/pbuilder-ev3dev base"
- git checkout -B ev3dev-$DIST
script:
- "/tmp/pbuilder-ev3dev build"
before_deploy:
- LICENSES='"LGPL-2.1", "GPL-2.0", "MIT"'
- "/tmp/pbuilder-ev3dev dpl"
deploy:
  on:
    tags: true
  provider: bintray
  file: "$HOME/bintray.json"
  user: dlech
  key:
    secure: BqVjdNKi3+EKlrc6vmCGTfI5U4VSiDKj3uhsEyRrxERm/ojvIbEfu3YtG2FX4Ug8wJcsHcg6D3+07KsH9HUvgL5JrJ8bxmCAXIAm5MfiMwyfjRoDBOXE0awpn5J4SyfFk/vxk+bVlvSp+fsjWvUrPjuqx7FdA1N4fR/2nEepzkw=
