language: bash
sudo: required
dist: trusty
env:
- OS=debian ARCH=amd64 DIST=stretch
- OS=debian ARCH=i386 DIST=stretch
- OS=debian ARCH=armhf DIST=stretch
- OS=raspbian ARCH=armhf DIST=stretch
- OS=debian ARCH=armel DIST=stretch
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository "deb http://archive.ev3dev.org/ubuntu trusty main"
- sudo apt-key adv --keyserver pgp.mit.edu --recv-keys D57D95AF93178A7C
- sudo apt-get update
- sudo apt-get install --yes pbuilder-ev3dev
- sudo ln -s /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/stretch
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-testing
script:
- pbuilder-ev3dev build
